//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mons151.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mons151.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Diploma_RB {
            get {
                object obj = ResourceManager.GetObject("Diploma_RB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;players&gt;
        ///  &lt;player&gt;
        ///    &lt;name&gt;Sam&lt;/name&gt;
        ///    &lt;time&gt;180&lt;/time&gt;
        ///    &lt;score&gt;151&lt;/score&gt;
        ///  &lt;/player&gt;
        ///  &lt;player&gt;
        ///    &lt;name&gt;Ben&lt;/name&gt;
        ///    &lt;time&gt;380&lt;/time&gt;
        ///    &lt;score&gt;151&lt;/score&gt;
        ///  &lt;/player&gt;
        ///  &lt;player&gt;
        ///    &lt;name&gt;Doyle&lt;/name&gt;
        ///    &lt;time&gt;100&lt;/time&gt;
        ///    &lt;score&gt;100&lt;/score&gt;
        ///  &lt;/player&gt;
        ///  &lt;player&gt;
        ///    &lt;name&gt;Reid&lt;/name&gt;
        ///    &lt;time&gt;160&lt;/time&gt;
        ///    &lt;score&gt;98&lt;/score&gt;
        ///  &lt;/player&gt;
        ///  &lt;player&gt;
        ///    &lt;name&gt;T&lt;/name&gt;
        ///    &lt;time&gt;45&lt;/time&gt;
        ///    &lt;score&gt;3&lt;/score&gt;
        ///  &lt;/player&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HighScores {
            get {
                return ResourceManager.GetString("HighScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pokemon_Research_Lab_Background {
            get {
                object obj = ResourceManager.GetObject("Pokemon_Research_Lab_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
